spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/intruder
    username: postgres
    password: root
  jpa:
    show-sql: true
    generate-ddl: true

  mustache:
    expose-request-attributes: true